#if !canImport(ObjectiveC)
import XCTest

extension AppGroupTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__AppGroupTests = [
        ("testAccessors", testAccessors),
        ("testCodable", testCodable),
        ("testEquatingAndHashing", testEquatingAndHashing),
        ("testFileSystem", testFileSystem),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(AppGroupTests.__allTests__AppGroupTests),
    ]
}
#endif
